package Forms;


import CRUD.DAO.MarksDAO;
import Common.PieChart;
import Models.Marks;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class ChartForm extends SimpleForm {
    private JPanel mainPanel;


    public ChartForm() {
        ArrayList<Marks> marks = new MarksDAO().getAll();
        int count[] = new int[5];
        for (int i = 0; i < marks.size(); i++)
            count[marks.get(i).mark - 1]++;
        ArrayList<Double> values = new ArrayList<Double>();
        for (int i = 0; i < count.length; i++) {
            double value = (double) count[i] / (double) marks.size();
            values.add(value * 100);
        }
        ArrayList<Color> colors = new ArrayList<Color>();
        colors.add(Color.gray);
        colors.add(Color.green);
        colors.add(Color.blue);
        colors.add(Color.pink);
        colors.add(Color.yellow);
        Dimension dimension1 = new Dimension(400, 400);
        Dimension dimension2 = new Dimension(250, 250);
        PieChart pieChart = new PieChart(values, colors);
        pieChart.setSize(dimension2);
        pieChart.setPreferredSize(dimension2);
        this.mainPanel = new JPanel();
        Open(mainPanel, dimension1);
        mainPanel.add(pieChart);
    }

    @Override
    public void AddListeners() {

    }

    @Override
    public void Close() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
